import { Inter } from "next/font/google";
import Body from "./body";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "First NextJS App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Body />
        {children}
      </body>
    </html>
  );
}
